import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const products = [
  {
    id: "giro-konto",
    name: "KT GiroKonto",
    category: "Comptes",
    icon: "💳",
    color: "#005F2D",
    tagline: "Le compte courant 100% halal",
    description: "Gérez votre argent au quotidien sans intérêts ni frais cachés. Notre compte courant respecte les principes de la finance islamique.",
    features: ["Sans frais de tenue de compte", "Carte Visa gratuite", "Virement instantané", "Application mobile", "IBAN allemand", "Sans intérêts (Halal)"],
    cta: "Ouvrir mon compte",
    badge: "Gratuit",
    popular: false,
  },
  {
    id: "gold-konto",
    name: "KT GoldKonto",
    category: "Investissement",
    icon: "🥇",
    color: "#C9A84C",
    tagline: "Investissez dans l'or physique dès 1€",
    description: "Combinez un compte bancaire moderne avec l'investissement en or physique certifié LBMA. Aucun frais de gestion.",
    features: ["Or physique certifié LBMA", "À partir de 1€", "Sans frais de gestion", "Rachat à tout moment", "Stockage sécurisé", "Rendement stable"],
    cta: "Ouvrir mon GoldKonto",
    badge: "Populaire",
    popular: true,
  },
  {
    id: "jetzz-card",
    name: "KT Jetzz Card",
    category: "Cartes",
    icon: "💳",
    color: "#1A1A2E",
    tagline: "Paiements flexibles sans frais annuels",
    description: "Profitez d'un paiement en plusieurs fois (3 à 24 mois) sans frais annuels. La carte parfaite pour vos achats.",
    features: ["Sans frais annuels", "3 à 24 mois de paiement", "Acceptée partout", "Notifications instantanées", "Plafond modulable", "Assurance voyage"],
    cta: "Demander ma carte",
    badge: "0€/an",
    popular: false,
  },
  {
    id: "vehicle-financing",
    name: "Financement Auto",
    category: "Financement",
    icon: "🚗",
    color: "#1E40AF",
    tagline: "Votre véhicule, sans intérêts",
    description: "Financez votre véhicule neuf ou d'occasion de manière conforme à la charia. Accord instantané, jusqu'à 100 mois.",
    features: ["Accord en 24h", "Jusqu'à 100 mois", "Véhicules neufs/occasion", "Sans intérêts (Murabaha)", "Financement jusqu'à 100%", "Assurance incluse possible"],
    cta: "Simuler mon financement",
    badge: "24h",
    popular: false,
  },
  {
    id: "personal-loans",
    name: "Crédit Personnel",
    category: "Financement",
    icon: "💰",
    color: "#7C3AED",
    tagline: "Jusqu'à 50 000€ en ligne",
    description: "Réalisez vos projets personnels avec notre crédit sans intérêts. Accord rapide, sans déplacement en agence.",
    features: ["Jusqu'à 50 000€", "Réponse en ligne", "Sans déplacement", "Taux fixe garanti", "Remboursement anticipé", "Halal certifié"],
    cta: "Faire ma demande",
    badge: "50K€",
    popular: false,
  },
  {
    id: "festgeld-konto",
    name: "KT FestgeldKonto",
    category: "Épargne",
    icon: "📈",
    color: "#059669",
    tagline: "Épargne sécurisée à rendement garanti",
    description: "Faites fructifier votre épargne avec des rendements au-dessus du marché, garantis et conformes à la finance islamique.",
    features: ["Rendement garanti", "Au-dessus du marché", "Durée flexible", "Sans frais", "Sécurisé BaFin", "Renouvellement auto"],
    cta: "Ouvrir un FestgeldKonto",
    badge: "Top Rendement",
    popular: false,
  },
  // NEW PRODUCTS
  {
    id: "donation",
    name: "KT Donation & Zakat",
    category: "Solidarité",
    icon: "🤲",
    color: "#D97706",
    tagline: "Zakat, Sadaqa & dons en ligne",
    description: "Gérez facilement votre Zakat, Sadaqa et dons caritatifs. Notre plateforme certifiée vous permet de faire le bien en toute transparence.",
    features: ["Calculateur Zakat intégré", "Projets caritatifs certifiés", "Suivi de vos dons", "Reçu fiscal automatique", "Partenaires ONG vérifiés", "Sadaqa Jariya"],
    cta: "Faire un don",
    badge: "Nouveau",
    popular: false,
    isNew: true,
  },
  {
    id: "corporate-credit",
    name: "Crédit Pro & PME",
    category: "Entreprise",
    icon: "🏢",
    color: "#0F172A",
    tagline: "Financez votre entreprise sans intérêts",
    description: "Solutions de financement islamique pour les entreprises : Musharaka, Mudaraba, Ijara. De la TPE aux grandes entreprises.",
    features: ["Musharaka & Mudaraba", "Jusqu'à 5M€", "Financement immobilier pro", "Crédit-bail Ijara", "Accompagnement dédié", "Décision en 72h"],
    cta: "Contacter un conseiller",
    badge: "Pro",
    popular: false,
    isNew: true,
  },
  {
    id: "youth-savings",
    name: "KT JugendKonto",
    category: "Jeunesse",
    icon: "🌱",
    color: "#10B981",
    tagline: "Épargne jeunesse pour les moins de 25 ans",
    description: "Initiez vos enfants à une épargne saine et halal. Compte d'épargne jeunesse avec bonus de bienvenue et rendements attractifs.",
    features: ["Dès 0 ans", "Bonus de bienvenue 50€", "Rendement préférentiel", "Parental control", "Sans frais jusqu'à 25 ans", "Éducation financière"],
    cta: "Ouvrir pour mon enfant",
    badge: "Jeunesse",
    popular: false,
    isNew: true,
  },
  {
    id: "real-estate",
    name: "Financement Immobilier",
    category: "Immobilier",
    icon: "🏠",
    color: "#B45309",
    tagline: "Votre maison, conformément à la charia",
    description: "Achetez votre bien immobilier grâce à nos solutions Murabaha et Diminishing Musharaka. Sans intérêts, en toute sérénité.",
    features: ["Murabaha immobilier", "Diminishing Musharaka", "Jusqu'à 30 ans", "Résidence principale/locatif", "Conseiller dédié", "Notaire partenaire"],
    cta: "Simuler mon projet",
    badge: "Immobilier",
    popular: false,
    isNew: true,
  },
];

export const stats = [
  { value: "150+", label: "Employés", icon: "👥" },
  { value: "4", label: "Agences en Allemagne", icon: "🏦" },
  { value: "50K+", label: "Clients satisfaits", icon: "⭐" },
  { value: "2015", label: "Fondée en", icon: "📅" },
];

export const branches = [
  {
    city: "Frankfurt",
    address: "Bockenheimer Landstraße 33, 60325 Frankfurt am Main",
    phone: "+49 69 2475 1700",
    hours: "Lun-Ven: 9h-17h",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400&q=80",
  },
  {
    city: "Berlin",
    address: "Wilmersdorfer Str. 50/51, 10627 Berlin",
    phone: "+49 30 3150 0450",
    hours: "Lun-Ven: 9h-17h",
    image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=400&q=80",
  },
  {
    city: "Cologne",
    address: "Venloer Str. 24, 50672 Cologne",
    phone: "+49 221 2758 5310",
    hours: "Lun-Ven: 9h-17h",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=400&q=80",
  },
  {
    city: "Munich",
    address: "Landsberger Str. 110, 80339 Munich",
    phone: "+49 89 4520 5700",
    hours: "Lun-Ven: 9h-17h",
    image: "https://images.unsplash.com/photo-1549921296-3b0f9a35af35?w=400&q=80",
  },
];

export const testimonials = [
  {
    name: "Ahmed K.",
    role: "Client depuis 2018",
    text: "KT Bank a changé ma façon de gérer mon argent. Enfin une banque qui respecte mes valeurs islamiques tout en offrant des services modernes.",
    rating: 5,
    avatar: "A",
  },
  {
    name: "Fatima M.",
    role: "Cliente depuis 2020",
    text: "Le GoldKonto est excellent. J'investis dans l'or physique en quelques clics. Le service client est toujours disponible et très professionnel.",
    rating: 5,
    avatar: "F",
  },
  {
    name: "Yusuf B.",
    role: "Client Entreprise",
    text: "Grâce au Crédit Pro, j'ai pu financer l'expansion de mon entreprise sans compromettre mes principes. Un accompagnement sur mesure remarquable.",
    rating: 5,
    avatar: "Y",
  },
  {
    name: "Mariam L.",
    role: "Cliente depuis 2021",
    text: "J'ai ouvert un JugendKonto pour mes enfants. C'est parfait pour les initier à l'épargne halal dès le jeune âge. Je recommande vivement.",
    rating: 5,
    avatar: "M",
  },
];
